# 应用名称
spring:
  application:
    name: my-multiple-versions-provider

# 配置dubbo
dubbo:
  registry:
    # 注册中心地址
    address: zookeeper://192.168.3.188
    port: 2181
  scan:
    base-packages: com.ghy.www.my.servicegoup.provider.service # 扫包
  provider:
    host: 192.168.3.188
  application:
    logger: slf4j