# 应用名称
spring:
  application:
    name: my-timeout-consumer

# 配置dubbo
dubbo:
  registry:
    # 注册中心地址
    address: zookeeper://192.168.3.188
    port: 2181
  application:
    logger: slf4j

server:
  port: 8085
