spring:
  application:
    name: my-check1

server:
  port: 8085

# 配置dubbo
dubbo:
  registry:
    # 注册中心地址
    address: zookeeper://192.168.3.188
    port: 2181
  reference:
    com.ghy.www.api.IService1.check: false
  application:
    logger: slf4j