# 应用名称
spring:
  application:
    name: my-implicit-parameters-consumer

server:
  port: 8085

# 配置dubbo
dubbo:
  registry:
    # 注册中心地址
    address: zookeeper://192.168.3.188
    port: 2181
  application:
    logger: slf4j